# config/packages/twig.yaml

twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    # /!\ Question de l'ECF /!\

when@test:
    twig:
        strict_variables: true
